package com.salesianos.dto_tarea.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

// @Entity --> No necesitamos que sea entidad pues no es una api rest, es para pruebas
// por ende, tampoco necesitamos hacer respos y services para este sample
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Alumno {

    // @AutogeneratedValue @Id
    private Long id;
    private String nombre;
    private String apellido1;
    private String apellido2;
    private String email;

    @Builder.Default // Testear en conjunto con las validacinoes
    private Direccion direccion;
    private Curso curso;


}
