package com.salesianos.dto_tarea.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

// @Entity --> No necesitamos que sea entidad pues no es una api rest, es para pruebas
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Alumno {

    // @AutogeneratedValue @Id
    private Long id;
    private String nombre;
    private String apellido1;
    private String apellido2;
    private int telefono;
    private String email;
    private String direccion; // Cambiar por las dos clases propias
    private String curso;


}
