package com.salesianos.dto_tarea.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

import javax.swing.*;

// @Entity
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Curso {

    // @AutogeneratedValue @Id
    private Long id;
    private String nombre;
    private String tipo;
    private Spring tutor;
    private enum aula{A, B, C};

}
