package com.salesianos.dto_tarea.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

// @Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Direccion {

    // @AutogeneratedValue @Id
    private Long id;
    private String tipoVia;
    private String linea1;
    private String linea2;
    private String cp;
    private String poblacion;
    private String provicia;

}
