package com.salesianos.tarea_dto_apartado_2.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

// @Entity --> No necesitamos que sea entidad pues no es una api rest, es para pruebas
// por ende, tampoco necesitamos hacer respos, services, etc para este sample
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Producto {
    // @AutogeneratedValue @Id
    private Long id;
    private String nombre;
    private String desc;
    private float pvp;
    private String images; // Para simplificar, pero debería ser tipo List<String>
    private Categoria categoria;
}

